# Generated by Django 5.2.15 on 2026-06-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('title', models.CharField(max_length=100, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('icon_class', models.CharField(default='fa-solid fa-music', help_text='Exemple : fa-solid fa-ring', max_length=120, verbose_name='classe icone Font Awesome')),
            ],
            options={
                'verbose_name': "type d'evenement",
                'verbose_name_plural': "types d'evenements",
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('icon_name', models.CharField(default='music', help_text='Exemples : music, users, volume-2, star.', max_length=80, verbose_name='icone Lucide')),
                ('title', models.CharField(max_length=80, verbose_name='titre ou chiffre')),
                ('text', models.CharField(max_length=120, verbose_name='texte')),
            ],
            options={
                'verbose_name': 'argument hero',
                'verbose_name_plural': 'arguments hero',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='titre principal')),
                ('subtitle', models.CharField(blank=True, max_length=180, verbose_name='sous-titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('background_image', models.FileField(blank=True, upload_to='hero/', verbose_name='image de fond')),
                ('quote_button_text', models.CharField(blank=True, max_length=80, verbose_name='texte bouton devis')),
                ('quote_button_url', models.CharField(default='#contact', max_length=200, verbose_name='lien bouton devis')),
                ('video_button_text', models.CharField(blank=True, max_length=80, verbose_name='texte bouton video')),
                ('video_button_url', models.CharField(default='#videos', max_length=200, verbose_name='lien bouton video')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'section hero',
                'verbose_name_plural': 'sections hero',
            },
        ),
        migrations.CreateModel(
            name='PerformanceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Une prestation complete', max_length=120, verbose_name='accroche')),
                ('title', models.CharField(max_length=180, verbose_name='titre')),
                ('image', models.FileField(blank=True, upload_to='performance/', verbose_name='image')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'section prestation',
                'verbose_name_plural': 'sections prestation',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Fiestacoustik', max_length=120, verbose_name='nom du site')),
                ('logo', models.FileField(blank=True, upload_to='site/', verbose_name='logo')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telephone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('location', models.CharField(blank=True, max_length=180, verbose_name='zone geographique')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('quote_button_text', models.CharField(default='Demander un devis', max_length=80, verbose_name='texte du bouton devis')),
                ('contact_eyebrow', models.CharField(default='Parlons de votre projet', max_length=120, verbose_name='accroche contact')),
                ('contact_title', models.CharField(default='Un evenement en preparation ?', max_length=160, verbose_name='titre contact')),
                ('contact_text', models.TextField(default='Remplissez le formulaire, je vous reponds rapidement pour en discuter.', verbose_name='texte contact')),
            ],
            options={
                'verbose_name': 'reglage du site',
                'verbose_name_plural': 'reglages du site',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('text', models.TextField(verbose_name='avis')),
                ('author_name', models.CharField(max_length=120, verbose_name='nom')),
                ('event_label', models.CharField(blank=True, max_length=120, verbose_name='evenement')),
            ],
            options={
                'verbose_name': 'avis client',
                'verbose_name_plural': 'avis clients',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telephone')),
                ('event_type_label', models.CharField(blank=True, max_length=120, verbose_name="type d'evenement saisi")),
                ('event_date', models.DateField(blank=True, null=True, verbose_name="date de l'evenement")),
                ('location', models.CharField(blank=True, max_length=180, verbose_name="lieu de l'evenement")),
                ('message', models.TextField(verbose_name='message')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('read', 'Lu'), ('done', 'Traite'), ('archived', 'Archive')], default='new', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eventtype', verbose_name="type d'evenement")),
            ],
            options={
                'verbose_name': 'demande de contact',
                'verbose_name_plural': 'demandes de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('text', models.CharField(max_length=180, verbose_name='texte')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='core.performancesection', verbose_name='section')),
            ],
            options={
                'verbose_name': 'point de prestation',
                'verbose_name_plural': 'points de prestation',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
