# Generated by Django 5.2.15 on 2026-06-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('title', models.CharField(max_length=120, verbose_name='titre')),
                ('subtitle', models.CharField(blank=True, max_length=140, verbose_name='sous-titre')),
                ('video_url', models.URLField(blank=True, verbose_name='URL de la video')),
                ('thumbnail', models.FileField(blank=True, upload_to='videos/', verbose_name='image miniature')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='En video', max_length=120, verbose_name='accroche')),
                ('title', models.CharField(default="Decouvrez l'ambiance en live", max_length=160, verbose_name='titre')),
                ('button_text', models.CharField(default='Voir toutes les videos', max_length=80, verbose_name='texte du bouton')),
                ('button_url', models.CharField(default='#videos', max_length=200, verbose_name='lien du bouton')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'section video',
                'verbose_name_plural': 'sections video',
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_company',
            field=models.CharField(default='Maguely', max_length=120, verbose_name='entreprise footer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(default='Creation de sites vitrines et experiences web sur mesure.', max_length=220, verbose_name='texte footer'),
        ),
    ]
