# Generated by Django 5.2.15 on 2026-07-01 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_videoitem_videosection_sitesettings_footer_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrequest',
            name='event_type',
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
        migrations.RemoveField(
            model_name='performancebullet',
            name='section',
        ),
        migrations.DeleteModel(
            name='VideoSection',
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
        migrations.DeleteModel(
            name='PerformanceBullet',
        ),
        migrations.DeleteModel(
            name='PerformanceSection',
        ),
    ]
